/**
 * hooks/useStarterCards.ts — Round 98.
 *
 * Pulls the pre-seeded starter deck generated by
 * `/api/onboarding/seed` when the user first entered their income.
 *
 * Contract:
 *   • Zero-txn first-open Home calls this BEFORE any real financial
 *     data exists. Returns an array of 3 deterministic action cards
 *     so the user sees something tappable in < 45s of app install.
 *   • Cached locally — once seeded, repeat reads are instant.
 *   • Silently returns `{ cards: [], seeded: false }` if the user
 *     never hit the income step (e.g. upgraded from an older build).
 */
import { useCallback, useEffect, useState } from 'react';
import api from '../utils/api';

export interface StarterCard {
  kind: 'set_budget_cap' | 'create_goal' | 'import_sms' | string;
  label: string;
  endpoint: string;
  method: 'POST' | 'GET' | 'PUT' | 'DELETE';
  payload: Record<string, any>;
  projected_impact?: number;
  projected_label?: string;
  confidence?: number;
  reason?: string;
  rank?: number;
}

export interface StarterCardsState {
  cards: StarterCard[];
  anchorPct: number | null;
  anchorCopy: string | null;
  diagnosticSeed: any | null;
  seeded: boolean;
  loading: boolean;
  error: string | null;
  refetch: () => Promise<void>;
}

export function useStarterCards(enabled: boolean = true): StarterCardsState {
  const [cards, setCards]                 = useState<StarterCard[]>([]);
  const [anchorPct, setAnchorPct]         = useState<number | null>(null);
  const [anchorCopy, setAnchorCopy]       = useState<string | null>(null);
  const [diagnosticSeed, setDiagnosticSeed] = useState<any | null>(null);
  const [seeded, setSeeded]               = useState(false);
  const [loading, setLoading]             = useState(false);
  const [error, setError]                 = useState<string | null>(null);

  const refetch = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await api.get('/onboarding/starter-cards');
      const d = res?.data ?? {};
      setCards(Array.isArray(d.cards) ? d.cards : []);
      setAnchorPct(typeof d.anchor_pct === 'number' ? d.anchor_pct : null);
      setAnchorCopy(d.anchor_copy || null);
      setDiagnosticSeed(d.diagnostic_seed || null);
      setSeeded(!!d.seeded);
    } catch (e: any) {
      // 401 / 404 → treat as not-seeded silently. We never want to
      // surface an error when the user just hasn't gone through the
      // income step yet.
      setCards([]);
      setSeeded(false);
      setError(e?.message || null);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (enabled) { refetch().catch(() => {}); }
  }, [enabled, refetch]);

  return { cards, anchorPct, anchorCopy, diagnosticSeed, seeded, loading, error, refetch };
}

export default useStarterCards;
