#!/usr/bin/env bash
# install-git-hooks.sh — wire /app/scripts/pre-commit-typecheck.sh into git.
#
# Idempotent. Safe to re-run after every clone or fresh checkout.
# Run once after cloning the repo:
#    bash /app/scripts/install-git-hooks.sh
#
# Why a trampoline instead of symlink?
#   • Symlinks break on Windows / some CI runners.
#   • A small shell script that execs the real hook is portable.

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
HOOK_DIR="$ROOT/.git/hooks"
HOOK="$HOOK_DIR/pre-commit"

mkdir -p "$HOOK_DIR"

cat > "$HOOK" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by /app/scripts/install-git-hooks.sh — do not edit directly.
ROOT="$(git rev-parse --show-toplevel)"
exec bash "$ROOT/scripts/pre-commit-typecheck.sh" "$@"
EOF

chmod +x "$HOOK"
chmod +x "$ROOT/scripts/pre-commit-typecheck.sh"

echo "✅ Git pre-commit hook installed at: $HOOK"
echo "   Trampolines to:                  $ROOT/scripts/pre-commit-typecheck.sh"
echo
echo "Test it now (no commit will be made if there are TS errors):"
echo "   git add -A && git commit -m 'test' --dry-run"
